# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Orthodox Brotherhood of St. Eustace  
email: orthodoxbrotherhood-steustace@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Founded in 2020 as a fellowship of men of Holly Archangels church of the Diocese of San Francisco and Western America of the Russian Orthodox Church Outside Russia (ROCOR).
baseurl: "/sub-directory"
url: "http://orthodoxbrotherhood-steustace.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

theme: jekyll-theme-midnight
